// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: gift.proto

package gift

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGiftRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetGiftRequest) Reset() {
	*x = GetGiftRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gift_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGiftRequest) ProtoMessage() {}

func (x *GetGiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gift_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGiftRequest.ProtoReflect.Descriptor instead.
func (*GetGiftRequest) Descriptor() ([]byte, []int) {
	return file_gift_proto_rawDescGZIP(), []int{0}
}

func (x *GetGiftRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGiftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gift *Gift `protobuf:"bytes,1,opt,name=gift,proto3" json:"gift,omitempty"`
}

func (x *GetGiftResponse) Reset() {
	*x = GetGiftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gift_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGiftResponse) ProtoMessage() {}

func (x *GetGiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gift_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGiftResponse.ProtoReflect.Descriptor instead.
func (*GetGiftResponse) Descriptor() ([]byte, []int) {
	return file_gift_proto_rawDescGZIP(), []int{1}
}

func (x *GetGiftResponse) GetGift() *Gift {
	if x != nil {
		return x.Gift
	}
	return nil
}

type ListGiftRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListGiftRequest) Reset() {
	*x = ListGiftRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gift_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGiftRequest) ProtoMessage() {}

func (x *ListGiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gift_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGiftRequest.ProtoReflect.Descriptor instead.
func (*ListGiftRequest) Descriptor() ([]byte, []int) {
	return file_gift_proto_rawDescGZIP(), []int{2}
}

type ListGiftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gifts []*Gift `protobuf:"bytes,1,rep,name=gifts,proto3" json:"gifts,omitempty"`
}

func (x *ListGiftResponse) Reset() {
	*x = ListGiftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gift_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGiftResponse) ProtoMessage() {}

func (x *ListGiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gift_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGiftResponse.ProtoReflect.Descriptor instead.
func (*ListGiftResponse) Descriptor() ([]byte, []int) {
	return file_gift_proto_rawDescGZIP(), []int{3}
}

func (x *ListGiftResponse) GetGifts() []*Gift {
	if x != nil {
		return x.Gifts
	}
	return nil
}

type AddGiftRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gift *Gift `protobuf:"bytes,1,opt,name=gift,proto3" json:"gift,omitempty"`
}

func (x *AddGiftRequest) Reset() {
	*x = AddGiftRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gift_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGiftRequest) ProtoMessage() {}

func (x *AddGiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gift_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGiftRequest.ProtoReflect.Descriptor instead.
func (*AddGiftRequest) Descriptor() ([]byte, []int) {
	return file_gift_proto_rawDescGZIP(), []int{4}
}

func (x *AddGiftRequest) GetGift() *Gift {
	if x != nil {
		return x.Gift
	}
	return nil
}

type AddGiftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddGiftResponse) Reset() {
	*x = AddGiftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gift_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGiftResponse) ProtoMessage() {}

func (x *AddGiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gift_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGiftResponse.ProtoReflect.Descriptor instead.
func (*AddGiftResponse) Descriptor() ([]byte, []int) {
	return file_gift_proto_rawDescGZIP(), []int{5}
}

func (x *AddGiftResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveGiftRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveGiftRequest) Reset() {
	*x = RemoveGiftRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gift_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveGiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGiftRequest) ProtoMessage() {}

func (x *RemoveGiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gift_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGiftRequest.ProtoReflect.Descriptor instead.
func (*RemoveGiftRequest) Descriptor() ([]byte, []int) {
	return file_gift_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveGiftRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveGiftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RemoveGiftResponse) Reset() {
	*x = RemoveGiftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gift_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveGiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGiftResponse) ProtoMessage() {}

func (x *RemoveGiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gift_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGiftResponse.ProtoReflect.Descriptor instead.
func (*RemoveGiftResponse) Descriptor() ([]byte, []int) {
	return file_gift_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveGiftResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReserveGiftRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReservedBy string `protobuf:"bytes,2,opt,name=reserved_by,json=reservedBy,proto3" json:"reserved_by,omitempty"`
}

func (x *ReserveGiftRequest) Reset() {
	*x = ReserveGiftRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gift_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveGiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveGiftRequest) ProtoMessage() {}

func (x *ReserveGiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gift_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveGiftRequest.ProtoReflect.Descriptor instead.
func (*ReserveGiftRequest) Descriptor() ([]byte, []int) {
	return file_gift_proto_rawDescGZIP(), []int{8}
}

func (x *ReserveGiftRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReserveGiftRequest) GetReservedBy() string {
	if x != nil {
		return x.ReservedBy
	}
	return ""
}

type ReserveGiftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ReserveGiftResponse) Reset() {
	*x = ReserveGiftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gift_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveGiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveGiftResponse) ProtoMessage() {}

func (x *ReserveGiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gift_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveGiftResponse.ProtoReflect.Descriptor instead.
func (*ReserveGiftResponse) Descriptor() ([]byte, []int) {
	return file_gift_proto_rawDescGZIP(), []int{9}
}

func (x *ReserveGiftResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Gift struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       float64 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Recipient   string  `protobuf:"bytes,5,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Reserved    bool    `protobuf:"varint,6,opt,name=reserved,proto3" json:"reserved,omitempty"`
	ReservedBy  string  `protobuf:"bytes,7,opt,name=reserved_by,json=reservedBy,proto3" json:"reserved_by,omitempty"`
}

func (x *Gift) Reset() {
	*x = Gift{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gift_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gift) ProtoMessage() {}

func (x *Gift) ProtoReflect() protoreflect.Message {
	mi := &file_gift_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gift.ProtoReflect.Descriptor instead.
func (*Gift) Descriptor() ([]byte, []int) {
	return file_gift_proto_rawDescGZIP(), []int{10}
}

func (x *Gift) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Gift) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Gift) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Gift) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Gift) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *Gift) GetReserved() bool {
	if x != nil {
		return x.Reserved
	}
	return false
}

func (x *Gift) GetReservedBy() string {
	if x != nil {
		return x.ReservedBy
	}
	return ""
}

var File_gift_proto protoreflect.FileDescriptor

var file_gift_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x69, 0x66, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x69,
	0x66, 0x74, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x69, 0x66, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x67, 0x69, 0x66, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x69, 0x66, 0x74, 0x2e, 0x47, 0x69, 0x66,
	0x74, 0x52, 0x04, 0x67, 0x69, 0x66, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x47,
	0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x10, 0x4c, 0x69,
	0x73, 0x74, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20,
	0x0a, 0x05, 0x67, 0x69, 0x66, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x67, 0x69, 0x66, 0x74, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x52, 0x05, 0x67, 0x69, 0x66, 0x74, 0x73,
	0x22, 0x30, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x67, 0x69, 0x66, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x67, 0x69, 0x66, 0x74, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x52, 0x04, 0x67, 0x69,
	0x66, 0x74, 0x22, 0x2b, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x23, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x47, 0x69,
	0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x45, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x47,
	0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x42, 0x79, 0x22, 0x2f, 0x0a, 0x13, 0x52,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xbd, 0x01, 0x0a,
	0x04, 0x47, 0x69, 0x66, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x42, 0x79, 0x32, 0xbd, 0x02, 0x0a,
	0x0b, 0x47, 0x69, 0x66, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x47, 0x69, 0x66, 0x74, 0x12, 0x14, 0x2e, 0x67, 0x69, 0x66, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x67, 0x69, 0x66, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x69, 0x66, 0x74,
	0x12, 0x15, 0x2e, 0x67, 0x69, 0x66, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x69, 0x66, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x69, 0x66, 0x74, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x36, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x47, 0x69, 0x66, 0x74, 0x12, 0x14, 0x2e, 0x67, 0x69, 0x66,
	0x74, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x67, 0x69, 0x66, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x69, 0x66, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x47, 0x69, 0x66, 0x74, 0x12, 0x17, 0x2e, 0x67, 0x69, 0x66, 0x74, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x67, 0x69, 0x66, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x47, 0x69, 0x66, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x47, 0x69, 0x66, 0x74, 0x12, 0x18, 0x2e, 0x67, 0x69, 0x66, 0x74, 0x2e, 0x52,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x67, 0x69, 0x66, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gift_proto_rawDescOnce sync.Once
	file_gift_proto_rawDescData = file_gift_proto_rawDesc
)

func file_gift_proto_rawDescGZIP() []byte {
	file_gift_proto_rawDescOnce.Do(func() {
		file_gift_proto_rawDescData = protoimpl.X.CompressGZIP(file_gift_proto_rawDescData)
	})
	return file_gift_proto_rawDescData
}

var file_gift_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_gift_proto_goTypes = []interface{}{
	(*GetGiftRequest)(nil),      // 0: gift.GetGiftRequest
	(*GetGiftResponse)(nil),     // 1: gift.GetGiftResponse
	(*ListGiftRequest)(nil),     // 2: gift.ListGiftRequest
	(*ListGiftResponse)(nil),    // 3: gift.ListGiftResponse
	(*AddGiftRequest)(nil),      // 4: gift.AddGiftRequest
	(*AddGiftResponse)(nil),     // 5: gift.AddGiftResponse
	(*RemoveGiftRequest)(nil),   // 6: gift.RemoveGiftRequest
	(*RemoveGiftResponse)(nil),  // 7: gift.RemoveGiftResponse
	(*ReserveGiftRequest)(nil),  // 8: gift.ReserveGiftRequest
	(*ReserveGiftResponse)(nil), // 9: gift.ReserveGiftResponse
	(*Gift)(nil),                // 10: gift.Gift
}
var file_gift_proto_depIdxs = []int32{
	10, // 0: gift.GetGiftResponse.gift:type_name -> gift.Gift
	10, // 1: gift.ListGiftResponse.gifts:type_name -> gift.Gift
	10, // 2: gift.AddGiftRequest.gift:type_name -> gift.Gift
	0,  // 3: gift.GiftService.GetGift:input_type -> gift.GetGiftRequest
	2,  // 4: gift.GiftService.ListGift:input_type -> gift.ListGiftRequest
	4,  // 5: gift.GiftService.AddGift:input_type -> gift.AddGiftRequest
	6,  // 6: gift.GiftService.RemoveGift:input_type -> gift.RemoveGiftRequest
	8,  // 7: gift.GiftService.ReserveGift:input_type -> gift.ReserveGiftRequest
	1,  // 8: gift.GiftService.GetGift:output_type -> gift.GetGiftResponse
	3,  // 9: gift.GiftService.ListGift:output_type -> gift.ListGiftResponse
	5,  // 10: gift.GiftService.AddGift:output_type -> gift.AddGiftResponse
	7,  // 11: gift.GiftService.RemoveGift:output_type -> gift.RemoveGiftResponse
	9,  // 12: gift.GiftService.ReserveGift:output_type -> gift.ReserveGiftResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_gift_proto_init() }
func file_gift_proto_init() {
	if File_gift_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gift_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGiftRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gift_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGiftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gift_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGiftRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gift_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGiftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gift_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGiftRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gift_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGiftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gift_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveGiftRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gift_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveGiftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gift_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReserveGiftRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gift_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReserveGiftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gift_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gift); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gift_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gift_proto_goTypes,
		DependencyIndexes: file_gift_proto_depIdxs,
		MessageInfos:      file_gift_proto_msgTypes,
	}.Build()
	File_gift_proto = out.File
	file_gift_proto_rawDesc = nil
	file_gift_proto_goTypes = nil
	file_gift_proto_depIdxs = nil
}
