name: Go Tests & Checks

on: [push]

jobs:
  test:
    name: Run Go Tests & Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: Verify module dependencies
        run: go mod tidy && git diff --exit-code

      - name: Run Go fmt
        run: go fmt ./...

      - name: Run Go vet
        run: go vet ./...

      - name: Run Go lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: backend  # Lint inside "backend/"

      - name: Run Go tests
        run: go test -v ./...

      - name: Run race detector (optional, for concurrency issues)
        run: go test -race ./...
