name: Go Tests & Lint

on: [push]

jobs:
  test:
    name: Run Go Tests & Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
          cache: true

      - name: Verify module dependencies
        run: go mod tidy && git diff --exit-code

      - name: Run Go fmt
        run: go fmt ./...

      - name: Run Go vet
        run: go vet ./...

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: backend
          args: --timeout=5m

      - name: Run Go tests with parallelism
        run: go test -v -p=4 ./...

      - name: Run race detector (for concurrency issues)
        run: go test -race ./...
